from collections import namedtuple

Genotype = namedtuple('Genotype', 'normal normal_concat reduce reduce_concat')

PRIMITIVES = [
    'none', 'max_pool_3x3', 'avg_pool_3x3', 'skip_connect', 'sep_conv_3x3',
    'sep_conv_5x5', 'dil_conv_3x3', 'dil_conv_5x5'
]
hdm05_sparsemax_1 = Genotype(normal=[('Skip_normal', 0), ('BiMap_1_normal', 1),
                                     ('Skip_normal', 0), ('Skip_normal', 2)],
                             normal_concat=range(2, 4),
                             reduce=[('BiMap_1_reduced', 0),
                                     ('BiMap_1_reduced', 1),
                                     ('BiMap_1_reduced', 1),
                                     ('BiMap_2_reduced', 0)],
                             reduce_concat=range(2, 4))
hdm05_sparsemax_2 = Genotype(normal=[('Skip_normal', 0), ('BiMap_2_normal', 1),
                                     ('Skip_normal', 0), ('Skip_normal', 2)],
                             normal_concat=range(2, 4),
                             reduce=[('BiMap_1_reduced', 0),
                                     ('BiMap_1_reduced', 1),
                                     ('MaxPooling_reduced', 0),
                                     ('BiMap_1_reduced', 1)],
                             reduce_concat=range(2, 4))
hdm05_relu = Genotype(normal=[('Skip_normal', 0), ('BiMap_1_normal', 1),
                              ('BiMap_2_normal', 0), ('Skip_normal', 2)],
                      normal_concat=range(2, 4),
                      reduce=[('BiMap_1_reduced', 0), ('BiMap_2_reduced', 1),
                              ('BiMap_2_reduced', 0), ('BiMap_2_reduced', 1)],
                      reduce_concat=range(2, 4))
radar_sparsemax = Genotype(normal=[('Skip_normal', 0), ('Skip_normal', 1),
                                   ('BiMap_0_normal', 0),
                                   ('BiMap_1_normal', 2)],
                           normal_concat=range(2, 4),
                           reduce=[('BiMap_2_reduced', 1),
                                   ('BiMap_2_reduced', 0),
                                   ('BiMap_1_reduced', 1),
                                   ('BiMap_2_reduced', 0)],
                           reduce_concat=range(2, 4))
v0_hdm05_gen6 = Genotype(normal=[('Skip_normal', 0), ('BiMap_1_normal', 1),
                                 ('BiMap_0_normal', 2), ('Skip_normal', 0)],
                         normal_concat=range(2, 4),
                         reduce=[('BiMap_1_reduced', 1), ('Skip_reduced', 0),
                                 ('Skip_reduced', 0),
                                 ('MaxPooling_reduced', 2)],
                         reduce_concat=range(2, 4))
v0_hdm05_gen8 = Genotype(normal=[('Skip_normal', 0), ('BiMap_2_normal', 1),
                                 ('Skip_normal', 0), ('Skip_normal', 2)],
                         normal_concat=range(2, 4),
                         reduce=[('MaxPooling_reduced', 1),
                                 ('MaxPooling_reduced', 0),
                                 ('MaxPooling_reduced', 1),
                                 ('MaxPooling_reduced', 0)],
                         reduce_concat=range(2, 4))
v0_hdm05_gen7 = Genotype(normal=[('Skip_normal', 0), ('BiMap_2_normal', 1),
                                 ('Skip_normal', 0), ('Skip_normal', 2)],
                         normal_concat=range(2, 4),
                         reduce=[('MaxPooling_reduced', 1),
                                 ('Skip_reduced', 0),
                                 ('MaxPooling_reduced', 1),
                                 ('MaxPooling_reduced', 0)],
                         reduce_concat=range(2, 4))
PRIMITIVES_SPDNet_v0 = [
    'none_normal', 'WeightedPooling_normal', 'BiMap_0_normal',
    'BiMap_1_normal', 'BiMap_2_normal', 'Skip_normal', 'none_reduced',
    'AvgPooling2_reduced', 'MaxPooling_reduced', 'BiMap_1_reduced',
    'BiMap_2_reduced', 'Skip_reduced'
]
#'BiMap_0_reduced',
PRIMITIVES_SPDNet_v1 = [
    'none_normal', 'AvgPooling_1_normal', 'DiMap_1_normal', 'DiMap_2_normal',
    'BiMap_1_normal', 'BiMap_2_normal', 'Skip_1_normal', 'none_reduced',
    'AvgPooling_2_reduced', 'MaxPooling_reduced', 'BiMap_0_reduced',
    'BiMap_1_reduced', 'BiMap_2_reduced', 'Skip_2_reduced'
]
NASNet = Genotype(
    normal=[
        ('sep_conv_5x5', 1),
        ('sep_conv_3x3', 0),
        ('sep_conv_5x5', 0),
        ('sep_conv_3x3', 0),
        ('avg_pool_3x3', 1),
        ('skip_connect', 0),
        ('avg_pool_3x3', 0),
        ('avg_pool_3x3', 0),
        ('sep_conv_3x3', 1),
        ('skip_connect', 1),
    ],
    normal_concat=[2, 3, 4, 5, 6],
    reduce=[
        ('sep_conv_5x5', 1),
        ('sep_conv_7x7', 0),
        ('max_pool_3x3', 1),
        ('sep_conv_7x7', 0),
        ('avg_pool_3x3', 1),
        ('sep_conv_5x5', 0),
        ('skip_connect', 3),
        ('avg_pool_3x3', 2),
        ('sep_conv_3x3', 2),
        ('max_pool_3x3', 1),
    ],
    reduce_concat=[4, 5, 6],
)
hdm05_sparse_final = Genotype(normal=[('Skip_normal', 0), ('Skip_normal', 1),
                                      ('BiMap_2_normal', 0),
                                      ('BiMap_2_normal', 2)],
                              normal_concat=range(2, 4),
                              reduce=[('BiMap_1_reduced', 0),
                                      ('BiMap_1_reduced', 1),
                                      ('BiMap_2_reduced', 0),
                                      ('BiMap_1_reduced', 1)],
                              reduce_concat=range(2, 4))
hdm05_sigmoid_2 = Genotype(normal=[('Skip_normal', 0), ('BiMap_2_normal', 1),
                                   ('BiMap_2_normal', 0), ('Skip_normal', 2)],
                           normal_concat=range(2, 4),
                           reduce=[('BiMap_1_reduced', 0), ('Skip_reduced', 1),
                                   ('MaxPooling_reduced', 0),
                                   ('MaxPooling_reduced', 1)],
                           reduce_concat=range(2, 4))

radar_sigmoid2 = Genotype(normal=[('Skip_normal', 0), ('Skip_normal', 1),
                                  ('Skip_normal', 0), ('Skip_normal', 2)],
                          normal_concat=range(2, 4),
                          reduce=[('MaxPooling_reduced', 1),
                                  ('MaxPooling_reduced', 0),
                                  ('MaxPooling_reduced', 1),
                                  ('BiMap_2_reduced', 0)],
                          reduce_concat=range(2, 4))

#hdm05_sparsemax = Genotype(normal=[('Skip_normal', 0), ('BiMap_1_normal', 1), ('Skip_normal', 0), ('Skip_normal', 2)], normal_concat=range(2, 4), reduce=[('BiMap_1_reduced', 0), ('BiMap_1_reduced', 1), ('BiMap_1_reduced', 1), ('BiMap_2_reduced', 0)], reduce_concat=range(2, 4))
radar_sparse1_0_75 = Genotype(normal=[[('Skip_normal', 0), ('Skip_normal', 1)],
                                      [('BiMap_0_normal', 0)]],
                              normal_concat=range(2, 4),
                              reduce=[[('BiMap_2_reduced', 0),
                                       ('BiMap_2_reduced', 1)],
                                      [('BiMap_1_reduced', 1),
                                       ('BiMap_2_reduced', 0)]],
                              reduce_concat=range(2, 4))
radar_sparse1_0_25 = Genotype(normal=[[('Skip_normal', 0), ('Skip_normal', 1)],
                                      [('BiMap_0_normal', 0),
                                       ('Skip_normal', 1),
                                       ('BiMap_1_normal', 2)]],
                              normal_concat=range(2, 4),
                              reduce=[[('BiMap_2_reduced', 0),
                                       ('BiMap_2_reduced', 1)],
                                      [('BiMap_2_reduced', 0),
                                       ('MaxPooling_reduced', 1),
                                       ('BiMap_1_reduced', 1),
                                       ('BiMap_0_normal', 2),
                                       ('Skip_normal', 2)]],
                              reduce_concat=range(2, 4))
radar_sparse1_0_5 = Genotype(normal=[[('Skip_normal', 0), ('Skip_normal', 1)],
                                     [('BiMap_0_normal', 0),
                                      ('BiMap_1_normal', 2)]],
                             normal_concat=range(2, 4),
                             reduce=[[('BiMap_2_reduced', 0),
                                      ('BiMap_2_reduced', 1)],
                                     [('BiMap_2_reduced', 0),
                                      ('BiMap_1_reduced', 1)]],
                             reduce_concat=range(2, 4))
radar_sparse1_0_1 = Genotype(normal=[[('Skip_normal', 0), ('Skip_normal', 1)],
                                     [('BiMap_0_normal', 0),
                                      ('BiMap_0_normal', 1),
                                      ('Skip_normal', 1),
                                      ('WeightedPooling_normal', 2),
                                      ('BiMap_1_normal', 2)]],
                             normal_concat=range(2, 4),
                             reduce=[[('BiMap_2_reduced', 0),
                                      ('Skip_reduced', 0),
                                      ('MaxPooling_reduced', 1),
                                      ('BiMap_2_reduced', 1)],
                                     [('BiMap_1_reduced', 0),
                                      ('BiMap_2_reduced', 0),
                                      ('Skip_reduced', 0),
                                      ('MaxPooling_reduced', 1),
                                      ('BiMap_1_reduced', 1),
                                      ('BiMap_0_normal', 2),
                                      ('BiMap_2_normal', 2),
                                      ('Skip_normal', 2)]],
                             reduce_concat=range(2, 4))

radar_sparse2_0_75 = Genotype(normal=[[('Skip_normal', 0)],
                                      [('Skip_normal', 0)]],
                              normal_concat=range(2, 4),
                              reduce=[[('MaxPooling_reduced', 1),
                                       ('MaxPooling_reduced', 0)],
                                      [('MaxPooling_reduced', 1),
                                       ('MaxPooling_reduced', 0)]],
                              reduce_concat=range(2, 4))
radar_dum_sparse2_0_5 = Genotype(normal=[[('Skip_normal', 0)],
                                         [('Skip_normal', 0),
                                          ('Skip_normal', 2)]],
                                 normal_concat=range(2, 4),
                                 reduce=[[('MaxPooling_reduced', 1)],
                                         [('MaxPooling_reduced', 1)]],
                                 reduce_concat=range(2, 4))
radar_sparse2_0_25 = Genotype(normal=[[('Skip_normal', 0),
                                       ('BiMap_0_normal', 1),
                                       ('Skip_normal', 1)],
                                      [('Skip_normal', 0), ('Skip_normal', 1),
                                       ('WeightedPooling_normal', 2),
                                       ('Skip_normal', 2)]],
                              normal_concat=range(2, 4),
                              reduce=[[('MaxPooling_reduced', 0),
                                       ('MaxPooling_reduced', 1),
                                       ('BiMap_1_reduced', 1)],
                                      [('MaxPooling_reduced', 0),
                                       ('BiMap_2_reduced', 0),
                                       ('MaxPooling_reduced', 1),
                                       ('BiMap_1_reduced', 1)]],
                              reduce_concat=range(2, 4))
test = Genotype(normal=[[('Skip_normal', 0), ('Skip_normal', 1)],
                        [('Skip_normal', 0), ('Skip_normal', 2)]],
                normal_concat=range(2, 4),
                reduce=[
                    [('MaxPooling_reduced', 1)],
                    [('MaxPooling_reduced', 1)],
                ],
                reduce_concat=range(2, 4))
radar_sparse2_0_5 = Genotype(normal=[[('Skip_normal', 0)],
                                     [('Skip_normal', 0), ('Skip_normal', 2)]],
                             normal_concat=range(2, 4),
                             reduce=[[('MaxPooling_reduced', 1)],
                                     [('MaxPooling_reduced', 1)]],
                             reduce_concat=range(2, 4))
radar_sparse2_0_1 = Genotype(normal=[[('Skip_normal', 0),
                                      ('WeightedPooling_normal', 1),
                                      ('BiMap_0_normal', 1),
                                      ('BiMap_1_normal', 1),
                                      ('BiMap_2_normal', 1),
                                      ('Skip_normal', 1)],
                                     [('WeightedPooling_normal', 0),
                                      ('Skip_normal', 0),
                                      ('BiMap_0_normal', 1),
                                      ('BiMap_1_normal', 1),
                                      ('BiMap_2_normal', 1),
                                      ('Skip_normal', 1),
                                      ('WeightedPooling_normal', 2),
                                      ('Skip_normal', 2)]],
                             normal_concat=range(2, 4),
                             reduce=[[('MaxPooling_reduced', 0),
                                      ('BiMap_1_reduced', 0),
                                      ('BiMap_2_reduced', 0),
                                      ('Skip_reduced', 0),
                                      ('MaxPooling_reduced', 1),
                                      ('BiMap_1_reduced', 1),
                                      ('BiMap_2_reduced', 1)],
                                     [('MaxPooling_reduced', 0),
                                      ('BiMap_1_reduced', 0),
                                      ('BiMap_2_reduced', 0),
                                      ('Skip_reduced', 0),
                                      ('MaxPooling_reduced', 1),
                                      ('BiMap_1_reduced', 1),
                                      ('BiMap_2_reduced', 1),
                                      ('WeightedPooling_normal', 2),
                                      ('BiMap_0_normal', 2),
                                      ('BiMap_1_normal', 2),
                                      ('BiMap_2_normal', 2),
                                      ('Skip_normal', 2)]],
                             reduce_concat=range(2, 4))
hdm05_sparse1_0_75 = Genotype(normal=[[('Skip_normal', 0)],
                                      [('Skip_normal', 0),
                                       ('Skip_normal', 2)]],
                              normal_concat=range(2, 4),
                              reduce=[[('BiMap_1_reduced', 0),
                                       ('BiMap_1_reduced', 1)],
                                      [('MaxPooling_reduced', 0),
                                       ('BiMap_1_reduced', 1)]],
                              reduce_concat=range(2, 4))
hdm05_sparse1_0_25 = Genotype(normal=[[('Skip_normal', 0)],
                                      [('Skip_normal', 0),
                                       ('Skip_normal', 2)]],
                              normal_concat=range(2, 4),
                              reduce=[[('BiMap_1_reduced', 0),
                                       ('BiMap_1_reduced', 1),
                                       ('BiMap_2_reduced', 1)],
                                      [('MaxPooling_reduced', 0),
                                       ('BiMap_1_reduced', 1)]],
                              reduce_concat=range(2, 4))
hdm05_sparse1_0_1 = Genotype(normal=[[('Skip_normal', 0),
                                      ('WeightedPooling_normal', 1),
                                      ('BiMap_0_normal', 1),
                                      ('BiMap_1_normal', 1),
                                      ('BiMap_2_normal', 1),
                                      ('Skip_normal', 1)],
                                     [('Skip_normal', 0),
                                      ('WeightedPooling_normal', 1),
                                      ('BiMap_0_normal', 1),
                                      ('BiMap_1_normal', 1),
                                      ('BiMap_2_normal', 1),
                                      ('Skip_normal', 1), ('Skip_normal', 2)]],
                             normal_concat=range(2, 4),
                             reduce=[[('MaxPooling_reduced', 0),
                                      ('BiMap_1_reduced', 0),
                                      ('BiMap_2_reduced', 0),
                                      ('Skip_reduced', 0),
                                      ('MaxPooling_reduced', 1),
                                      ('BiMap_1_reduced', 1),
                                      ('BiMap_2_reduced', 1),
                                      ('Skip_reduced', 1)],
                                     [('MaxPooling_reduced', 0),
                                      ('BiMap_1_reduced', 0),
                                      ('BiMap_2_reduced', 0),
                                      ('Skip_reduced', 0),
                                      ('MaxPooling_reduced', 1),
                                      ('BiMap_1_reduced', 1),
                                      ('BiMap_2_reduced', 1),
                                      ('Skip_reduced', 1),
                                      ('WeightedPooling_normal', 2),
                                      ('BiMap_0_normal', 2),
                                      ('BiMap_1_normal', 2),
                                      ('BiMap_2_normal', 2),
                                      ('Skip_normal', 2)]],
                             reduce_concat=range(2, 4))
hdm05_sparse2_0_75 = Genotype(normal=[[('Skip_normal', 0)],
                                      [('Skip_normal', 0),
                                       ('Skip_normal', 2)]],
                              normal_concat=range(2, 4),
                              reduce=[[('BiMap_1_reduced', 0),
                                       ('BiMap_1_reduced', 1)],
                                      [('BiMap_1_reduced', 1),
                                       ('BiMap_2_reduced', 0)]],
                              reduce_concat=range(2, 4))
hdm05_sparse2_0_25 = Genotype(normal=[[('Skip_normal', 0)],
                                      [('Skip_normal', 0),
                                       ('Skip_normal', 2)]],
                              normal_concat=range(2, 4),
                              reduce=[[('BiMap_1_reduced', 0),
                                       ('BiMap_1_reduced', 1),
                                       ('BiMap_2_reduced', 1)],
                                      [('BiMap_1_reduced', 1),
                                       ('BiMap_2_reduced', 0)]],
                              reduce_concat=range(2, 4))
hdm05_sparse2_0_5 = Genotype(normal=[[('Skip_normal', 0)],
                                     [('Skip_normal', 0), ('Skip_normal', 2)]],
                             normal_concat=range(2, 4),
                             reduce=[[('BiMap_1_reduced', 0),
                                      ('BiMap_1_reduced', 1)],
                                     [('MaxPooling_reduced', 0),
                                      ('BiMap_1_reduced', 1)]],
                             reduce_concat=range(2, 4))
hdm05_sparse2_0_1 = Genotype(normal=[[('Skip_normal', 0),
                                      ('WeightedPooling_normal', 1),
                                      ('BiMap_0_normal', 1),
                                      ('BiMap_1_normal', 1),
                                      ('BiMap_2_normal', 1),
                                      ('Skip_normal', 1)],
                                     [('Skip_normal', 0),
                                      ('WeightedPooling_normal', 1),
                                      ('BiMap_0_normal', 1),
                                      ('BiMap_1_normal', 1),
                                      ('BiMap_2_normal', 1),
                                      ('Skip_normal', 1), ('Skip_normal', 2)]],
                             normal_concat=range(2, 4),
                             reduce=[[('MaxPooling_reduced', 0),
                                      ('BiMap_1_reduced', 0),
                                      ('BiMap_2_reduced', 0),
                                      ('Skip_reduced', 0),
                                      ('MaxPooling_reduced', 1),
                                      ('BiMap_1_reduced', 1),
                                      ('BiMap_2_reduced', 1),
                                      ('Skip_reduced', 1)],
                                     [('MaxPooling_reduced', 0),
                                      ('BiMap_1_reduced', 0),
                                      ('BiMap_2_reduced', 0),
                                      ('Skip_reduced', 0),
                                      ('MaxPooling_reduced', 1),
                                      ('BiMap_1_reduced', 1),
                                      ('BiMap_2_reduced', 1),
                                      ('Skip_reduced', 1),
                                      ('WeightedPooling_normal', 2),
                                      ('BiMap_0_normal', 2),
                                      ('BiMap_1_normal', 2),
                                      ('BiMap_2_normal', 2),
                                      ('Skip_normal', 2)]],
                             reduce_concat=range(2, 4))

radar3 = Genotype(normal=[('Skip_normal', 0), ('BiMap_0_normal', 1),
                          ('Skip_normal', 0), ('Skip_normal', 2)],
                  normal_concat=range(2, 4),
                  reduce=[('MaxPooling_reduced', 1), ('MaxPooling_reduced', 0),
                          ('MaxPooling_reduced', 1),
                          ('MaxPooling_reduced', 0)],
                  reduce_concat=range(2, 4))

radar2 = Genotype(normal=[('Skip_normal', 0), ('BiMap_0_normal', 1),
                          ('Skip_normal', 0), ('Skip_normal', 2)],
                  normal_concat=range(2, 4),
                  reduce=[('BiMap_1_reduced', 1), ('BiMap_1_reduced', 0),
                          ('MaxPooling_reduced', 1), ('BiMap_2_reduced', 0)],
                  reduce_concat=range(2, 4))

radar1 = Genotype(normal=[('Skip_normal', 0), ('BiMap_0_normal', 1),
                          ('Skip_normal', 0), ('Skip_normal', 2)],
                  normal_concat=range(2, 4),
                  reduce=[('MaxPooling_reduced', 1), ('MaxPooling_reduced', 0),
                          ('AvgPooling2_reduced', 1),
                          ('MaxPooling_reduced', 0)],
                  reduce_concat=range(2, 4))
random1 = Genotype(normal=[('BiMap_1_normal', 1), ('BiMap_2_normal', 0),
                           ('Skip_normal', 0), ('BiMap_2_normal', 2)],
                   normal_concat=range(2, 4),
                   reduce=[('BiMap_2_reduced', 0), ('Skip_reduced', 1),
                           ('MaxPooling_reduced', 1), ('BiMap_1_reduced', 0)],
                   reduce_concat=range(2, 4))
random2 = Genotype(normal=[('Skip_normal', 0), ('BiMap_1_normal', 1),
                           ('BiMap_0_normal', 0),
                           ('WeightedPooling_normal', 1)],
                   normal_concat=range(2, 4),
                   reduce=[('BiMap_2_reduced', 0), ('BiMap_1_reduced', 1),
                           ('BiMap_2_reduced', 0), ('BiMap_1_reduced', 1)],
                   reduce_concat=range(2, 4))
hdm05_2_cell_2 = Genotype(normal=[('WeightedPooling_normal', 0),
                                  ('BiMap_2_normal', 1), ('BiMap_1_normal', 1),
                                  ('WeightedPooling_normal', 0)],
                          normal_concat=range(2, 4),
                          reduce=[('MaxPooling_reduced', 1),
                                  ('AvgPooling2_reduced', 0),
                                  ('AvgPooling2_reduced', 0),
                                  ('MaxPooling_reduced', 1)],
                          reduce_concat=range(2, 4))
hdm05_2_cell_1 = Genotype(normal=[('BiMap_1_normal', 1), ('BiMap_2_normal', 0),
                                  ('WeightedPooling_normal', 1),
                                  ('WeightedPooling_normal', 2)],
                          normal_concat=range(2, 4),
                          reduce=[('AvgPooling2_reduced', 1),
                                  ('AvgPooling2_reduced', 0),
                                  ('AvgPooling2_reduced', 0),
                                  ('AvgPooling2_reduced', 1)],
                          reduce_concat=range(2, 4))
hdm051 = Genotype(normal=[('Skip_normal', 1), ('WeightedPooling_normal', 0),
                          ('Skip_normal', 1), ('WeightedPooling_normal', 0)],
                  normal_concat=range(2, 4),
                  reduce=[
                      ('AvgPooling2_reduced', 1), ('AvgPooling2_reduced', 0),
                      ('AvgPooling2_reduced', 2), ('AvgPooling2_reduced', 0)
                  ],
                  reduce_concat=range(2, 4))
hdm051 = Genotype(normal=[('Skip_normal', 1), ('WeightedPooling_normal', 0),
                          ('Skip_normal', 1), ('WeightedPooling_normal', 0)],
                  normal_concat=range(2, 4),
                  reduce=[
                      ('AvgPooling2_reduced', 1), ('AvgPooling2_reduced', 0),
                      ('AvgPooling2_reduced', 2), ('AvgPooling2_reduced', 0)
                  ],
                  reduce_concat=range(2, 4))
afew1 = Genotype(normal=[('Skip_normal', 0), ('Skip_normal', 1),
                         ('Skip_normal', 0), ('Skip_normal', 2)],
                 normal_concat=range(2, 4),
                 reduce=[
                     ('AvgPooling2_reduced', 1), ('AvgPooling2_reduced', 0),
                     ('AvgPooling2_reduced', 1), ('AvgPooling2_reduced', 0)
                 ],
                 reduce_concat=range(2, 4))
random1 = Genotype(normal=[('BiMap_1_normal', 1), ('BiMap_2_normal', 0),
                           ('Skip_normal', 0), ('BiMap_2_normal', 2)],
                   normal_concat=range(2, 4),
                   reduce=[('BiMap_2_reduced', 0), ('Skip_reduced', 1),
                           ('MaxPooling_reduced', 1), ('BiMap_1_reduced', 0)],
                   reduce_concat=range(2, 4))
random2 = Genotype(normal=[('Skip_normal', 0), ('BiMap_1_normal', 1),
                           ('BiMap_0_normal', 0),
                           ('WeightedPooling_normal', 1)],
                   normal_concat=range(2, 4),
                   reduce=[('BiMap_2_reduced', 0), ('BiMap_1_reduced', 1),
                           ('BiMap_2_reduced', 0), ('BiMap_1_reduced', 1)],
                   reduce_concat=range(2, 4))
v0_hdm05_gen6 = Genotype(normal=[('Skip_normal', 0), ('BiMap_1_normal', 1),
                                 ('BiMap_0_normal', 2), ('Skip_normal', 0)],
                         normal_concat=range(2, 4),
                         reduce=[('BiMap_1_reduced', 1), ('Skip_reduced', 0),
                                 ('Skip_reduced', 0),
                                 ('MaxPooling_reduced', 2)],
                         reduce_concat=range(2, 4))
v0_hdm05_gen8 = Genotype(normal=[('Skip_normal', 0), ('BiMap_2_normal', 1),
                                 ('Skip_normal', 0), ('Skip_normal', 2)],
                         normal_concat=range(2, 4),
                         reduce=[('MaxPooling_reduced', 1),
                                 ('MaxPooling_reduced', 0),
                                 ('MaxPooling_reduced', 1),
                                 ('MaxPooling_reduced', 0)],
                         reduce_concat=range(2, 4))
v0_hdm05_gen7 = Genotype(normal=[('Skip_normal', 0), ('BiMap_2_normal', 1),
                                 ('Skip_normal', 0), ('Skip_normal', 2)],
                         normal_concat=range(2, 4),
                         reduce=[('MaxPooling_reduced', 1),
                                 ('Skip_reduced', 0),
                                 ('MaxPooling_reduced', 1),
                                 ('MaxPooling_reduced', 0)],
                         reduce_concat=range(2, 4))
AmoebaNet = Genotype(normal=[
    ('avg_pool_3x3', 0),
    ('max_pool_3x3', 1),
    ('sep_conv_3x3', 0),
    ('sep_conv_5x5', 2),
    ('sep_conv_3x3', 0),
    ('avg_pool_3x3', 3),
    ('sep_conv_3x3', 1),
    ('skip_connect', 1),
    ('skip_connect', 0),
    ('avg_pool_3x3', 1),
],
                     normal_concat=[4, 5, 6],
                     reduce=[
                         ('avg_pool_3x3', 0),
                         ('sep_conv_3x3', 1),
                         ('max_pool_3x3', 0),
                         ('sep_conv_7x7', 2),
                         ('sep_conv_7x7', 0),
                         ('avg_pool_3x3', 1),
                         ('max_pool_3x3', 0),
                         ('max_pool_3x3', 1),
                         ('conv_7x1_1x7', 0),
                         ('sep_conv_3x3', 5),
                     ],
                     reduce_concat=[3, 4, 6])

DARTS_V1 = Genotype(normal=[('sep_conv_3x3', 1), ('sep_conv_3x3', 0),
                            ('skip_connect', 0), ('sep_conv_3x3', 1),
                            ('skip_connect', 0), ('sep_conv_3x3', 1),
                            ('sep_conv_3x3', 0), ('skip_connect', 2)],
                    normal_concat=[2, 3, 4, 5],
                    reduce=[('max_pool_3x3', 0), ('max_pool_3x3', 1),
                            ('skip_connect', 2), ('max_pool_3x3', 0),
                            ('max_pool_3x3', 0), ('skip_connect', 2),
                            ('skip_connect', 2), ('avg_pool_3x3', 0)],
                    reduce_concat=[2, 3, 4, 5])
DARTS_V2 = Genotype(normal=[('sep_conv_3x3', 0), ('sep_conv_3x3', 1),
                            ('sep_conv_3x3', 0), ('sep_conv_3x3', 1),
                            ('sep_conv_3x3', 1), ('skip_connect', 0),
                            ('skip_connect', 0), ('dil_conv_3x3', 2)],
                    normal_concat=[2, 3, 4, 5],
                    reduce=[('max_pool_3x3', 0), ('max_pool_3x3', 1),
                            ('skip_connect', 2), ('max_pool_3x3', 1),
                            ('max_pool_3x3', 0), ('skip_connect', 2),
                            ('skip_connect', 2), ('max_pool_3x3', 1)],
                    reduce_concat=[2, 3, 4, 5])
sp2 = Genotype(normal=[('Skip_normal', 0), ('BiMap_2_normal', 1),
                       ('Skip_normal', 0), ('Skip_normal', 2)],
               normal_concat=range(2, 4),
               reduce=[('BiMap_1_reduced', 0), ('BiMap_1_reduced', 1),
                       ('MaxPooling_reduced', 0), ('BiMap_1_reduced', 1)],
               reduce_concat=range(2, 4))
sp3 = Genotype(normal=[('Skip_normal', 0), ('BiMap_2_normal', 1),
                       ('Skip_normal', 0), ('Skip_normal', 2)],
               normal_concat=range(2, 4),
               reduce=[('BiMap_1_reduced', 0), ('BiMap_1_reduced', 1),
                       ('MaxPooling_reduced', 0), ('MaxPooling_reduced', 1)],
               reduce_concat=range(2, 4))
sp1 = Genotype(normal=[('Skip_normal', 0), ('BiMap_1_normal', 1),
                       ('Skip_normal', 0), ('Skip_normal', 2)],
               normal_concat=range(2, 4),
               reduce=[('BiMap_1_reduced', 0), ('BiMap_1_reduced', 1),
                       ('BiMap_1_reduced', 1), ('BiMap_2_reduced', 0)],
               reduce_concat=range(2, 4))
hdm05_sig = Genotype(normal=[('Skip_normal', 0), ('Skip_normal', 1),
                             ('Skip_normal', 0), ('Skip_normal', 2)],
                     normal_concat=range(2, 4),
                     reduce=[('BiMap_1_reduced', 0), ('BiMap_1_reduced', 1),
                             ('BiMap_1_reduced', 1), ('BiMap_2_reduced', 0)],
                     reduce_concat=range(2, 4))
hdm05_sigmoid3 = Genotype(normal=[('Skip_normal', 0), ('Skip_normal', 1),
                                  ('Skip_normal', 0), ('Skip_normal', 2)],
                          normal_concat=range(2, 4),
                          reduce=[
                              ('BiMap_1_reduced', 0), ('BiMap_1_reduced', 1),
                              ('BiMap_1_reduced', 1), ('BiMap_2_reduced', 0)
                          ],
                          reduce_concat=range(2, 4))
DARTS = DARTS_V2
